---
- hosts: all
  connection: local

  vars_files:
    - vars/main.yml
    - vars/welkin.yml

  roles:
    # need to remove defaults from homebrew somehow
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/oh-my-zsh.yml

    - include: tasks/python.yml

    - homebrew_cask: name={{ item }}
      with_items: "{{ homebrew_cask_apps_tom }}"

    - copy:
        src: files/spectacle/Shortcuts.json
        dest: ~/Library/Application Support/Spectacle/Shortcuts.json

    # welkin stuff

    - git: repo=https://github.com/welkinhealth/welkin.git
           dest={{ welkin_git_checkout }}
           update=no

    - include: tasks/welkin-tasks.yml

    #- include: tasks/preferences.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    #- name: Run .osx dotfiles.
    #  shell: ~/.osx --no-restart
    #  changed_when: false
