---
- hosts: all
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.dotfiles

  tasks:
    # common
    - include: tasks/ansible-setup.yml

    # for some reason oh-my-zsh re-prompts for sudo password
    - include: tasks/oh-my-zsh.yml

    # Some caskroom apps are in this tap
    - name: "Tap caskroom/drivers"
      command: brew tap caskroom/drivers

    # first need to make sure packages are "present" then need to link them as a separate step
    - name: "Install homebrew packages"
      homebrew: name={{ item }} state="present"
      with_items: "{{ homebrew_installed_packages_tom }}"

    - name: "Link homebrew packages"
      homebrew: name={{ item }} state="linked"
      with_items: "{{ homebrew_installed_packages_tom }}"

    - name: "Install homebrew cask apps"
      homebrew_cask: name={{ item }}
      with_items: "{{ homebrew_cask_apps_tom }}"

    - include: tasks/preferences.yml

    - name: "Use Git credential helper"
      command: git config --global credential.helper osxkeychain