---

# App-specific preferences
- name: Install Spectacle shortcut pref file
  copy:
    src: files/spectacle/Shortcuts.json
    dest: ~/Library/Application Support/Spectacle/Shortcuts.json

- name: Install SSH config file
  copy:
    src: files/ssh/config
    dest: ~/.ssh/config

- name: Add SSH key to agent
  command: ssh-add -K ~/.ssh/id_rsa

# Dock
- name: remove crap from the dock
  command: dockutil --remove all

# MacOS defaults
- osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: YES

- osx_defaults:
    domain: com.apple.CrashReporter
    key: DialogType
    value: developer

- osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

- osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2

- osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 25

- osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfDe

- osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: file://${HOME}/Desktop/

- osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

- osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true

